bot:
  name: YuukoBot
  prefix: "!"          # prefixo dos comandos
  environment: "development"

database:
  driver: sqlite3
  dsn: "file:storage/storage.db?_foreign_keys=on"

log:
  level: debug         # debug | info | warn | error

usersJID:
  owner: "seu_jid@lid" # JID do dono do bot (aparece no log ao iniciar)
  admins: []           # JIDs adicionais com permissão de admin

apiUrls:
  geocoding: "https://nominatim.openstreetmap.org/search"
  openMeteoGeo: "https://geocoding-api.open-meteo.com/v1/search"
  weather: "https://api.open-meteo.com/v1/forecast"

scheduledJobs:
  - name: "sextou"
    day: "friday"
    enabled: true
    hour: 10
    minute: 0
    audioPath: "assets/audios/play_tv.ogg"
    stickerName: "play_tv"
    targetGroups:
      - "grupo_jid@lid"
  # - name: "segunda"
  #   day: "monday"
  #   enabled: false
  #   hour: 9
  #   minute: 0
  #   audioPath: "assets/audios/segunda.ogg"
  #   targetGroups:
  #     - "grupo_jid@lid"
      # - "outro_grupo@lid"